### ISSUE TITLE
Support advanced properties

### ISSUE THREAD

**Issue by harlowja** [pschmitt/pykeepass#1]
It seems like in (at least) keepass 2.x files that more than just the fixed set of properties can be used. For example I can make properties with the following names (this is from the decoded saved XML)

```
          <String>
            <Key>ggggg</Key>
            <Value>ggggsa</Value>
          </String>
          <String>
            <Key>sdfsdf</Key>
            <Value>s</Value>
          </String>
```

This is quite useful for a certain application we have that uses these custom properties to store (like `ldap full CN`) that shouldn't belong in notes (because it's an actual property). Seems like something simple to support; btw when trying to make a new 'custom/advanced' property using one of the restricted names (URL, Notes...) the UI basically doesn't let you (so it would make sense for the code to disallow that to).

**Comment by pschmitt** [comment]
Indeed that would be nice. I won't have time to implement this in the next weeks, I'll try to tackle that when I get back home. PRs are welcome though o:)

**Comment by pschmitt** [comment]
Well I lied ;)

**Comment by harlowja** [comment]
Thanks much btw; didn't expect such quick turnaround!
