### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by drcursor** [pschmitt/pykeepass#13]
I installed this using pip3 and ran around in circles trying to solve the following error :

    >>> from pykeepass import PyKeePass
    Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
    ImportError: No module named 'pykeepass'`

Took me some time to figure out that this project is only running correctly under Python 2.

This should be made clear on the documentation.

**Comment by pschmitt** [comment]
I added a line to the README in 96ad69204d764261414113bf768a328795cc4395. I'll leave this issue open nonetheless since Python 3 compatibility is a must have in my opinion.
