### ISSUE TITLE
Question about release cadence

### ISSUE THREAD

**Issue by whwright** [pschmitt/pykeepass#139]
I was wondering if there any cadence set for releases or if they are just ad-hoc. There hasn't been a release since September of last year, but quite a few fixes have gone into master branch since then. Could we get a new pypi release published with these changes, or are you holding off for a `3.1.0` at some point?

I am willing to help out with things if you need an extra set of hands.

**Comment by singuliere** [comment]
@pschmitt ping?

**Comment by pschmitt** [comment]
@whwright There's no real release policy. It's just randomness and chaos ;)

I just released 3.0.3: https://pypi.org/project/pykeepass/3.0.3/

**Comment by whwright** [comment]
Awesome well that answers my question, and thanks for the release!
