### ISSUE TITLE
KeePassX : Unable to open the database. Invalid bool value

### ISSUE THREAD

**Issue by drcursor** [pschmitt/pykeepass#14]
Steps to reproduce

- create blank password file with keepassx
- pip install pykeepass
- Run with python

_

    from pykeepass import PyKeePass
    kp = PyKeePass('new.kdbx', password='test')
    kp.add_entry(kp.root_group, 'gmail', 'myusername', 'myPassw0rdXX')
    kp.save()

- Open file in keepassx

Interestingly enough, if I **just** create groups, the file is still readable.
eg.

    group = kp.add_group(kp.root_group,'a1')
    group2 = kp.add_group(group,'a2')`

**Comment by Evidlo** [comment]
I reported this yesterday with KeepassXC (fork of KeepassX) and it just got patched: https://github.com/keepassxreboot/keepassxc/pull/425

Alternatively, you could use the original Keepass.

I would recommend KeepassXC, as they seem to be in more active development.

**Comment by pschmitt** [comment]
Fixed in 3c7b4f0cfa75a531fdf91ea51306c89b29556e30
