### ISSUE TITLE
Trying to search and use a group after creating it fails

### ISSUE THREAD

**Issue by sacalo** [pschmitt/pykeepass#151]
```
from pykeepass import PyKeePass

kp = PyKeePass('db.kdbx', password='somePassw0rd')

grp = kp.add_group(kp.root_group, 'newGrp')
foundGrp = kp.find_groups_by_path('newGrp/')

# This works
kp.add_entry(grp, title='title', username='root', password='asdfasdf') 

# This fails
kp.add_entry(foundGrp, title='title', username='root', password='asdfasdf') 
```

> Traceback (most recent call last):
>   File ".../pykeepass_test.py", line 11, in <module>
>     kp.add_entry(grp, title='asews', username='root', password='asdfasdf')
>   File ".../pykeepass/pykeepass.py", line 413, in add_entry
>     recursive=False
>   File ".../pykeepass/pykeepass.py", line 311, in find_entries
>     res = self._find(prefix, entry_xp, path=path, tree=group, **kwargs)
>   File ".../pykeepass/pykeepass.py", line 212, in _find
>     tree=tree._element if tree else None,
> AttributeError: 'list' object has no attribute '_element'

**Comment by sacalo** [comment]
Nevermind, I wasnt accessing the group elements.

**Comment by Evidlo** [comment]
`find_groups_by_path` is deprecated by the way.
