### ISSUE TITLE
How to find a partial path?

### ISSUE THREAD

**Issue by duhlig** [pschmitt/pykeepass#163]
I need to find entries with the last group name and entry title like this: SERVERNAME/SUPERUSER. When I use find_entries_by_path I need to know at least the level in the group tree:

find_entries_by_path('.*/.*/.*/SERVERNAME/SUPERUSER', first=True, regex = True)

But unfortunately server names are in the 3rd, 4th or 5th level and I don't know whether this will change in future. So how to search for superuser X of the server Y?

Kind regards,
Dietmar

**Comment by Evidlo** [comment]
You can use xpath expressions to do this

``` python
>>> kp.entries
[Entry: "root_entry (foobar_user)",
 Entry: "foobar_entry (foobar)",
 Entry: "testing_new (lkj)",
 Entry: "quote test -> " <- (None)",
 Entry: "foobar_group/group_entry (foobar_user)",
 Entry: "foobar_group/foobar_entry (foobar)",
 Entry: "foobar_group/subgroup/subentry (foobar)",
 Entry: "foobar_group/subgroup/subentry2 (foobar)",
 Entry: "foobar_group/subgroup/foobar_entry (foobar)",
 Entry: "Работа/Тест (p)"]

>>> kp._xpath('//Group/Name[text()="subgroup"]/../Entry/String/Key[text()="Title"]/../Value[text()="foobar_entry"]/../..', first=True, cast=True)
Entry: "foobar_group/subgroup/foobar_entry (foobar)"
```

**Comment by Evidlo** [comment]
@duhlig Does this fix your issue?

**Comment by duhlig** [comment]
Sorry for my late reply. Your solution works. - Thank you.
In the mean time I was thinking about reordering my KeePass entries so that I can search this way:

```
kp.find_entries(title=servername, username=username, first=True, regex=True)
```

instead of the harder to read:

```
kp._xpath('//Group/Name[re:test(text(), "' + servername + '", "")]/../Entry/String/Key[text()="Title"]/../Value[re:test(text(), "' + username + '", "")]/../..', first=True, cast=True)
```

Anyway, the issue is solved. I will close it.

Kind Regards,
Dietmar
