### ISSUE TITLE
Entries are defined only by their group and by their title

### ISSUE THREAD

**Issue by mattLLVW** [pschmitt/pykeepass#27]
Hello,
Currently, entries are only defined during creation by their tree(group) and title.
Even if their username and password is different it overwrite it.
With the force_creation, t's possible to, but i think it's safer to check also at least the username before overwriting it.
Would you accept a pull request on this?
Thank you

**Comment by pschmitt** [comment]
Maybe. Would you rather have an exception raised if an entry with the same path and username exists?

**Comment by mattLLVW** [comment]
i think to check on the path, title and username could be nice because in the same path, there could be same username but different title, and (as this is my case) same title but different username.

I also found out that it's not possible to change group icon when creating one, should i make another issue on this?
i'm willing to contribute if needed.

**Comment by pschmitt** [comment]
Yeah, please open a new issue for that. PRs are always welcome.

**Comment by Evidlo** [comment]
Throwing an exception is the more axiomatic solution in my opinion, as entries are currently wholly defined by their path (including title) and most functions depend on this assumption.

If we decide to support entries with the same path and title, we need to update `entry.__str__` so entries with the same path, but different usernames are distinguishable

Functionally what these changes amount to is including the username in the entry path.  I would argue that a cleaner way to get multiple usernames per site is to create a group for the site and add entries with the usernames as titles.

**Comment by mattLLVW** [comment]
In my commit, i am already throwing an exception as discussed. 

Entries with the same path but different usernames are already distinguishable thanks to the path property returning the path and title of the entry.

> add a function for searching entries by username + title

I actually wanted to refactor __find_entry_by to take kwargs in the form of:
`find_entry_by(self, regex=False, tree=None, history=False, first=False, **kwargs)`
So you could easily pass any amount of kwargs, like title, username, password, url....
I think it would be an improvement.
Let me know if you're interested.

**Comment by Evidlo** [comment]
Why can't you create a group for the site where you want multiple usernames and just set the entry titles to the usernames when you create them?  I can't see any downsides to this approach.

Also, I double checked and entries with the same title but difference usernames are not distinguishable, unless I'm misunderstanding what you're saying.

[img](http://i.imgur.com/4NGiIej.png)

**Comment by mattLLVW** [comment]
Using an already established database with a thousand of entries, it is not possible to change the naming scheme.

> Also, I double checked and entries with the same title but difference usernames are not distinguishable, unless I'm misunderstanding what you're saying.

Sorry i was referring to the title property, but you are right, we should update` __str__` to add the title.

@pschmitt are you willing to merge something like this plus a function like the one i described(`find_entry_by(self, regex=False, tree=None, history=False, first=False, **kwargs`)?

**Comment by pschmitt** [comment]
+1 for adding the title to the string representation of an entry
