### ISSUE TITLE
Let programs decide the log level/config (and not pykeepass)

### ISSUE THREAD

**Issue by harlowja** [pschmitt/pykeepass#3]
Seems like there is a stray 'logging.basicConfig(level=logging.DEBUG)' when you import pykeepass; this is sorta a pain in the ass since my application using pykeepass wants to setup the logging level at program execution time, and not have pykeepass try to set it up itself...

Can we please remove that line & let applications using this library do the configuration (when they want). Thanks.

**Comment by bronger** [comment]
Thanks to @Evidlo, it re-appeared the second time. See PR https://github.com/libkeepass/pykeepass/pull/191.
