### ISSUE TITLE
Case insensitive regex

### ISSUE THREAD

**Issue by JimOL** [pschmitt/pykeepass#36]
This line:
lstEntry = kp.find_entries_by_notes(".*Chocolate.*",regex=True)
...finds the entry with notes:
Chocolate chips are a great invention

However, I cannot make the regex case-insensitive using the "i" modifier. I have tried these:
lstEntry = kp.find_entries_by_notes("/.*chocolate.*/i",regex=True)
lstEntry = kp.find_entries_by_notes("(.*chocolate.*)i",regex=True)

but both fail to find "Chocolate". Is this a bug in the regex or is there another way to make the search case insensitive?
Thanks

**Comment by pschmitt** [comment]
I don't believe that case insensitive regexes work right now.
There should be a parameter to pass here in order to enable that: https://github.com/pschmitt/pykeepass/blob/master/pykeepass/pykeepass.py#L151

Maybe using `text()[matches(.,'test', 'i')]``?

**Comment by JimOL** [comment]
Hi Philipp

 

I changed your search string as shown, and it works:

 

 xp = './/Entry/String/Key[text()="{}"]/../Value[re:test(text(), "{}","i")]/../..'.format(

                key, value

 

I think you could add another named argument to your __find_entry_by method and another  elif to cover case-insensitive:

 

def __find_entry_by(self, key, value, regex=False, tree=None,

                        history=False, first=False, caseInsensitive=False):

        if regex:

            xp = './/Entry/String/Key[text()="{}"]/../Value[re:test(text(), "{}")]/../..'.format(

                key, value

            )

            if caseInsensitive:

                xp = './/Entry/String/Key[text()="{}"]/../Value[re:test(text(), "{}","i")]/../..'.format(

                key, value

        else:

            xp = './/Entry/String/Key[text()="{}"]/../Value[text()="{}"]/../..'.format(

                key, value

            )

Thanks for all your work on pykeepass.

 

Jim
