### ISSUE TITLE
exslt regex link not valid

### ISSUE THREAD

**Issue by laerus** [pschmitt/pykeepass#41]
the [exslt regex link](https://github.com/pschmitt/pykeepass/blob/master/pykeepass/pykeepass.py#L79) doesn't seem to be valid anymore,
not sure what the right url should be

**Comment by pschmitt** [comment]
Whut?

**Comment by Evidlo** [comment]
Do you mean the XSLT link in the readme?  Seems to work for me.

**Comment by laerus** [comment]
uh wrong line, on `pykeepass/pykeepass.py` [line 81](https://github.com/pschmitt/pykeepass/blob/master/pykeepass/pykeepass.py#L81) the link [http://exslt.org/regular-expressions](http://exslt.org/regular-expressions)

**Comment by pschmitt** [comment]
Yeah that's just a namespace, not a URL for your browser.
