### ISSUE TITLE
find entries by kwargs

### ISSUE THREAD

**Issue by mattLLVW** [pschmitt/pykeepass#54]
Instead of having 8 different functions to find entries, it would be nice to just pass kwargs to `_find_entry_by`.

This way, you can actually find entries by multiple parameters, i.e:
`find_entries(title=exemple, username=me...)`

Would you consider a PR for this?

**Comment by pschmitt** [comment]
Yes, that'd be lit.

**Comment by Evidlo** [comment]
You might have a hard time integrating `find_entries_by_path` and `find_entry_by_uuid`, since these don't use `_find_entry_by` currently.  Also, if you merge all the `find_entries_by_*` functions, it would be prudent to do the same for `find_groups_by_*` to keep the api consistent.

**Comment by mattLLVW** [comment]
I actually did not wanted to break compatibility, so just expose `find_entry_by`, something like:
```
def find_entry_by(self, regex=False, flags=None,
                       tree=None, history=False, first=False, **kwargs):
```
Call it like this:
```
find_entry_by(regex=True, flags='i', first=True, Title='Root_entry', UserName='foobar_user', URL= 'http://example.com')
```

And keep `find_entries_by_title`,`find_entries_by_username`:
```
    def find_entries_by_title(self, title, regex=False, flags=None,
                              tree=None, history=False, first=False):
        return self.find_entry_by(
            regex=regex,
            flags=flags,
            tree=tree,
            history=history,
            first=first,
            Title=title
        )
```
But, yes, if we break retro-compatibility, find_entries and find_groups must be consistent.
@pschmitt @Evidlo , your call.

**Comment by pschmitt** [comment]
I'd rather have only one `find_entry`, screw retro-compatibility.

**Comment by pschmitt** [comment]
I'd prefer we keep the existing `find_entries_by_X`. These can then be implemented by simply calling `return find_entries_by(X=Z)`
