### ISSUE TITLE
feature request: ability to search custom fields

### ISSUE THREAD

**Issue by leupo** [pschmitt/pykeepass#65]
First of all: Thanks a lot for that lib.
My database entries are clearly idetified by a custom filed + username.  I can extract that custom fields with: get_custom_property() , but i want for search it. Could you implement that?

**Comment by Evidlo** [comment]
This should be closed.

**Comment by leupo** [comment]
Thank you so much Evidlo!

**Comment by Evidlo** [comment]
@pschmitt Could you push this to pypi?

**Comment by pschmitt** [comment]
Done: https://pypi.python.org/pypi/pykeepass/2.8.1
