### ISSUE TITLE
Suggestion to clarify readme

### ISSUE THREAD

**Issue by janos97** [pschmitt/pykeepass#7]
If I may suggest, the documentation could be significantly clarified with the following modification.

The function 'add_entry' seems to expect that 'group' is the object created earlier from the pk.find_entry_by_title() example.

`# write a new entry
pk.add_entry(
   group,
   'new_entry',
   'myusername',
   'myPassw0rdXX'
)`

Referencing an object for 'group' yields the following error:
`AttributeError: 'Group' object has no attribute 'lstrip'`

Providing a string instead of object works perfectly:
`# write a new entry
pk.add_entry(
   'group_name',
   'new_entry',
   'myusername',
   'myPassw0rdXX'
)`

Alternatively you could probably add in a check for isinstance(group, pykeepass.group.Group) to check if the variable is the object, then refer to group.name. Of course, this is a bit more work than just changing a few characters on the readme (^_^)

**Comment by pschmitt** [comment]
Thanks for reporting that. I'll fix that.
