### ISSUE TITLE
String field Enable in-memory protection.

### ISSUE THREAD

**Issue by teucrus** [pschmitt/pykeepass#89]
Hello,
Sorry of this exists, but I need to set the Enable in-memory protection option in the string fields.
I am creating and export script to convert some entries I have to a keepass database, but the application used to read the resulted database, needs some custonm string fields. I can add those no proplem with that, but I also need to set the Enable in-memory protection option for it to work.

Is it possible to implement that or give me some direction on how to implement that myself?

Thank you.

**Comment by Evidlo** [comment]
Try calling `kp.kdb.protect()` after loading the database.

**Comment by Evidlo** [comment]
Your custom string field needs to have `Protected="False"` for the above to work.

``` xml
<String>
  <Key>custom_field</Key>
  <Value Protected="False" ProtectedValue="KU3955/k">foobar</Value>
</String>
```

**Comment by teucrus** [comment]
Thank you for the reply but I don't think we mean the same thing.

What I need is to enable the option marked in the screenshot when adding a new entry.

![image](https://user-images.githubusercontent.com/8190132/43864478-78d989fe-9b68-11e8-9cea-277b61f078c3.png)

**Comment by Evidlo** [comment]
``` python
for e in entries:
    e._element.xpath('String/Key[text()="my_field"]/..')[0].attrib['protected'] = 'False'

kp.kdb.protect()
```

**Comment by teucrus** [comment]
Thanks a lot for the help.
