### ISSUE TITLE
Destructor function is missing

### ISSUE THREAD

**Issue by ichbestimmtnicht** [pschmitt/pykeepass#95]
Please add a .close() and or .save_and_close() function to gently quit the database.

**Comment by Evidlo** [comment]
This is implemented in parse_file() in the construct lib: https://github.com/construct/construct/blob/master/construct/core.py#L324

When you leave the block with `return` the fd is closed as mentioned in [this SO post](https://stackoverflow.com/questions/9885217/in-python-if-i-return-inside-a-with-block-will-the-file-still-close/39929765).
